defaults:
  - model: BiEncoderContrastiveModel
  - datamodule: GeneToken
  - split: split_mouse
  - _self_

wandb:
  enabled: true
  run_id: null
  run_name: actual_run
  entity: iacopodipippo-technical-university-of-munich
  project: scConcept

  
  
PATH:
  PROJECT_PATH: /p/home/jusers/dipippo1/jureca/projects/scConcept-1
  PROJECT_DATA_PATH: /p/project1/hai_fzj_bda/spitzer2/point_transformer/data/raw
  SCRATCH_ROOT: /p/scratch/cjinm16/dipippo1
  CHECKPOINT_ROOT: ${SCRATCH_ROOT}/model_checkpoints
  DATASET_PATH: ${PATH.PROJECT_DATA_PATH}
  ADATA_PATH: ${PATH.DATASET_PATH}
  PANELS_PATH: ${PATH.PROJECT_PATH}/various/panels/mouse
  LOCAL_DIR: null
  SPLIT: ${split}
  #TO CHANGE MAYBE I NEED TO CREATE
  label_encoders_path: ${PATH.PROJECT_PATH}/various/label_encoders.joblib
  gene_mapping_path: ${PATH.PROJECT_PATH}/various/pc_gene_token_mapping.pkl